#!/bin/bash

function usage {
    echo "usage: $programname [options value]"
    echo "	--author 	determines the file used for reading the name of the author requested the tests"
    echo "	--srcdir 	determines the directory used as source of pdf plotfiles"
    echo "	--dst    	determines the path for the output"
    exit 1
}


if [  $# -le 1 ] 
then 
  usage
  exit 1
fi 

DST="report.tex"

while [[ $# > 1 ]]
do
key="$1"

case $key in
    --author)
    REPORTAUTHOR="$2"
    shift # past argument
    ;;
    --srcdir)
    SRCDIR="$2"
    shift # past argument
    ;;
    --dst)
    DST="$2"
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
    # unknown option
    ;;
esac
shift # past argument or value
done

echo "" > $DST

echo "\documentclass[a4paper]{article}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage[colorinlistoftodos]{todonotes}
\usepackage{pdfpages}
\usepackage{url}

\title{
Constant Available Capacity with Single RMCAT flow\\\[1cm]
\large \textbf{AUTOMATIC TEST REPORT}\\\[1cm]
}


\author{
Requested by 
AUTHORREPLACESTRING
}

\date{\today}

\begin{document}
\maketitle
" >> $DST

sed -e '/AUTHORREPLACESTRING/ {' -e 'r '$REPORTAUTHOR -e 'd' -e '}' -i $DST

echo "
\begin{abstract}
This report is generated by testscript found in\cite{mprtp_gstreamer_github}. It is intended to show results of tests performed on Multipath RTP Gstreamer plugin according to \cite{rmcat_test_draft}.
\end{abstract}

\section{Test Description}

In this test case the bottleneck-link capacity between the two
endpoints remains constant over time. This test is designed to measure 
the stability of the cancdidate algorithm.

\textbf{Expected behavior}: the candidate algorithm is expected to detect the
path capacity constraint, converges to bottleneck link's capacity and
adapt the flow to avoid unwanted oscillation when the sending bit
rate is approaching the bottleneck link's capacity.  

\begin{figure}
\begin{verbatim}
                            Forward -->
+---+       +-----+                               +-----+       +---+
|S1 |=======|  A  |------------------------------>|  B  |=======|R1 |
+---+       |     |<------------------------------|     |       +---+
            +-----+                               +-----+
                         <-- Backward
\end{verbatim}
\caption{RTP transmission testcase topology}
\label{fig:ascii-box}
\end{figure}

" >> $DST

echo "
\pagebreak
\section{Results}

The choosen algorithm is a multiple-$\tau$ auocorrelation based congestion controller algorithm.

\begin{figure}[h]
\begin{verbatim}

TEXTTOREPLACE

\end{verbatim}
\caption{Parameters name and their values}
\label{fig:ascii-box}
\end{figure}


" >> $DST

FECPLOT="$SRCDIR/fec.pdf"
PLAYOUTPLOT="$SRCDIR/playouts.pdf"
AUTOCORRSPLOT="$SRCDIR/owd-autocorrs.pdf"
RCVTHROUGHPUTSPLOT="$SRCDIR/rcv-throughputs.pdf"
SNDTHROUGHPUTSPLOT="$SRCDIR/snd-throughputs.pdf"
RTCPINTVALSPLOT="$SRCDIR/rtcp-intervals.pdf"
CCPARAMS="$SRCDIR/ccparams_1.log"
STATFILE="$SRCDIR/stats.csv"

sed -e '/TEXTTOREPLACE/ {' -e 'r '$CCPARAMS -e 'd' -e '}' -i $DST

read GP_AVG GP_DEV FL_AVG FL_DEV LOSTS_AVG LOSTS_DEV< $STATFILE

echo "
\\\\
\begin{table}[h]
\centering
    \begin{tabular}{| l | l | l |}
    \hline
     & Avg. & Dev. \\\\ \hline
    Goodput & $GP_AVG & $GP_DEV \\\\ \hline
    Fraction lost & $FL_AVG & $FL_DEV \\\\ \hline
    Lost packets & $LOSTS_AVG & $LOSTS_DEV \\\\ \hline
    \hline
    \end{tabular}
\caption{Summarized statistics}
\label{table:1}
\end{table}\\\\
" >> $DST


echo "

\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$SNDTHROUGHPUTSPLOT}
    \caption{The measured throughputs at the sender side}
    \label{fig:sndthroughputs}
\end{figure}


\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$RCVTHROUGHPUTSPLOT}
    \caption{The measured throughputs at the receiver side}
    \label{fig:rcvthroughputs}
\end{figure}

\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$AUTOCORRSPLOT}
    \caption{Reported one way delays and their multiple-$\tau$ autocorrelations}
    \label{fig:mtauautocorrs}
\end{figure}

\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$PLAYOUTPLOT}
    \caption{Playout delays and queue size}
    \label{fig:playouts}
\end{figure}

\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$FECPLOT}
    \caption{Summary of FEC recovery}
    \label{fig:fec}
\end{figure}

\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$RTCPINTVALSPLOT}
    \caption{Summary of RTCP intervals}
    \label{fig:sumrtcpintervals}
\end{figure}

" >> $DST


echo "

\clearpage
\begin{thebibliography}{9}
\bibitem{mprtp_gstreamer_github}Multipath RTP implementations, \url{https://github.com/multipath-rtp}

\bibitem{rmcat_test_draft}Test Cases for Evaluating RMCAT Proposals, \url{https://tools.ietf.org/html/draft-ietf-rmcat-eval-test-02}

\end{thebibliography}

% copyright note
{% begin group
   \vspace*{65mm}
   \thispagestyle{empty}
   \footnotesize\itshape
   \setlength{\parskip}{\baselineskip}
   \setlength{\parindent}{0pt}
   \copyright\,2016, by Balázs Kreith

   All Rights Reserved.
}% end group
\end{document}

" >> $DST




