Vagrant.configure(2) do |config|

  config.vm.box = "trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.name = "gst-dev-env"
  end

  # config.vm.provision "shell", path: "startup.sh"

  config.vm.synced_folder "../", "/home/ubuntu/gst/dev"
  config.vm.network "private_network", ip: "192.168.199.2"
  config.vm.network "forwarded_port", guest: 3200, host: 3210

end
