Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.vm.synced_folder "log/lighttpd", "/var/log/lighttpd", owner: "www-data", group: "www-data", create: true

  config.vm.provision "shell", path: "startup.sh"

  config.vm.synced_folder "../", "/home/gst/dev"
  config.vm.network "private_network", ip: "192.168.199.2"
  config.vm.network "forwarded_port", guest: 3200, host: 3210

end
