#!/bin/bash

function usage {
    echo "usage: $programname [options value]"
    echo "	--author 	determines the file used for reading the name of the author requested the tests"
    echo "	--srcdir 	determines the directory used as source of pdf plotfiles"
    echo "	--dst    	determines the path for the output"
    exit 1
}


if [  $# -le 1 ] 
then 
  usage
  exit 1
fi 

DST="report.tex"

while [[ $# > 1 ]]
do
key="$1"

case $key in
    --author)
    REPORTAUTHOR="$2"
    shift # past argument
    ;;
    --srcdir)
    SRCDIR="$2"
    shift # past argument
    ;;
    --dst)
    DST="$2"
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
    # unknown option
    ;;
esac
shift # past argument or value
done

echo "" > $DST

echo "\documentclass[a4paper]{article}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage[colorinlistoftodos]{todonotes}
\usepackage{pdfpages}
\usepackage{url}

\title{
Competing Flows with Same RMCAT Algorithm\\\[1cm]
\large \textbf{AUTOMATIC TEST REPORT}\\\[1cm]
}


\author{
Requested by 
AUTHORREPLACESTRING
}

\date{\today}

\begin{document}
\maketitle
" >> $DST

sed -e '/AUTHORREPLACESTRING/ {' -e 'r '$REPORTAUTHOR -e 'd' -e '}' -i $DST

echo "
\begin{abstract}
This report is generated by testscript found in\cite{mprtp_gstreamer_github}. It is intended to show results of tests performed on Multipath RTP Gstreamer plugin according to \cite{rmcat_test_draft}.
\end{abstract}

\section{Test Description}

In this test case, more than one RMCAT media flow shares the
bottleneck link and each of them uses the same congestion control
algorithm.  This is a typical scenario where a real-time interactive
application sends more than one media flows to the same destination
and these flows are multiplexed over the same port.\\\

\textbf{Expected behavior}: It is expected that the competing flows will
   converge to an optimum bit rate to accommodate all the flows with
   minimum possible latency and loss.  Specifically, the test introduces
   three media flows at different time instances, when the second flow
   appears there should still be room to accommodate another flow on the
   bottleneck link.  Lastly, when the third flow appears the bottleneck
   link should be saturated.  

\begin{figure}
\begin{verbatim}
                            Forward -->
+---+       +-----+                               +-----+       +---+
|S1 |=======|  A  |------------------------------>|  B  |=======|R1 |
+---+       |     |<------------------------------|     |       +---+
            +-----+                               +-----+
                         <-- Backward
\end{verbatim}
\caption{RTP transmission testcase topology}
\label{fig:ascii-box}
\end{figure}

" >> $DST

echo "
\pagebreak
\section{Results}

" >> $DST

FECPLOT="$SRCDIR/fec.pdf"
RCVTHROUGHPUTSPLOT="$SRCDIR/rcv-throughputs.pdf"
SNDTHROUGHPUTSPLOT="$SRCDIR/snd-throughputs.pdf"

echo "

\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$SNDTHROUGHPUTSPLOT}
    \caption{The measured throughputs at the sender side}
    \label{fig:sndthroughputs}
\end{figure}


\begin{figure}[h]
    \centering
    \includegraphics[width=1\textwidth]{$RCVTHROUGHPUTSPLOT}
    \caption{The measured throughputs at the receiver side}
    \label{fig:rcvthroughputs}
\end{figure}

" >> $DST


echo "

\clearpage
\begin{thebibliography}{9}
\bibitem{mprtp_gstreamer_github}Multipath RTP implementations, \url{https://github.com/multipath-rtp}

\bibitem{rmcat_test_draft}Test Cases for Evaluating RMCAT Proposals, \url{https://tools.ietf.org/html/draft-ietf-rmcat-eval-test-02}

\end{thebibliography}

% copyright note
{% begin group
   \vspace*{65mm}
   \thispagestyle{empty}
   \footnotesize\itshape
   \setlength{\parskip}{\baselineskip}
   \setlength{\parindent}{0pt}
   \copyright\,2016, by Balázs Kreith

   All Rights Reserved.
}% end group
\end{document}

" >> $DST




